### ISSUE TITLE
appCache no longer used ?

### ISSUE THREAD

**Issue by Biboba** [Esri/maps-app-javascript#10]
Hi ! 
Thanks for this project : really nice to get started.
I notice that since the upgrade to webpack loader, appCache is no longer used but still mention in the Readme. 
Cheers

**Comment by odoe** [comment]
Oversight on my part, I'll add it back in today.

**Comment by odoe** [comment]
Fixed in latest https://github.com/Esri/maps-app-javascript/commit/86b7e39aa8e1c937d2e188dda2e66cb52d0bb001

Thanks!
